#!/bin/sh
# Builds the mobile app for Android arm64, packages it, installs and launches it
# on the attached phone.
#   ./build-android.sh          link + package + install + launch
#   ./build-android.sh link     just libphotowagon_arm64-v8a.so
#   ./build-android.sh package  the APK
#   ./build-android.sh run      install + launch + screenshot + logcat excerpt
#
# Prerequisites (see ../ANDROID.md): the LDC Android runtime referenced by
# toolchain/ldc2-android.conf, the DSide binding for the Qt Android kit
# (toolchain/build-binding.sh all), Qt 6.11 android_arm64_v8a + gcc_64 kits,
# SDK with NDK 27 and platform 36, JDK 17.
set -e

HERE=$(cd "$(dirname "$0")" && pwd)
DSIDE=${DSIDE:-$HOME/lab/qt-dlang-gen}
LDC_CONF=${LDC_CONF:-$HERE/toolchain/ldc2-android.conf}
QT_ANDROID=${QT_ANDROID:-$HOME/Qt/6.11.1/android_arm64_v8a}
QT_HOST=${QT_HOST:-$HOME/Qt/6.11.1/gcc_64}
NDK=${NDK:-/opt/android-sdk/ndk/27.2.12479018}
export ANDROID_SDK_ROOT=${ANDROID_SDK_ROOT:-/opt/android-sdk}
export JAVA_HOME=${JAVA_HOME:-/usr/lib/jvm/java-17-openjdk}
GEN=$DSIDE/generated/qt-6.11-android-arm64/cxx-quick
BUILD=$DSIDE/.build/qt-6.11-android-arm64-cxx-quick
APP=photowagon          # lib${APP}_${ABI}.so, the name QtActivity loads
ABI=arm64-v8a
OUT=$HERE/build-android
PKG_NAME=org.photowagon.mobile

for p in "$LDC_CONF" "$BUILD/libbinding_ldc2.a" "$BUILD/libshims.a" "$GEN/cxxrt.d"; do
    [ -e "$p" ] || { echo "missing: $p (see ../ANDROID.md)" >&2; exit 1; }
done
mkdir -p "$OUT"

# libp2p (lite: no webrtc transport, no c-ares), vibe-core, eventcore and the
# libsodium binding, as sources; libsodium itself is the archive in toolchain/android-libs.
DUBP=$HOME/.dub/packages
LIBP2P=$HERE/../../libp2p-dlang/source
P2P_INCLUDES="-I$LIBP2P"
P2P_SOURCES=$(find "$LIBP2P" -name '*.d' | grep -v '/transport/webrtc/' | grep -v 'dns_cares.d')
for d in eventcore-0.9.39/eventcore vibe-core-2.14.0/vibe-core vibe-container-1.7.1/vibe-container taggedalgebraic-1.0.1/taggedalgebraic stdx-allocator-2.77.5/stdx-allocator libsodiumd-0.2.0_1.0.18/libsodiumd; do
    [ -d "$DUBP/$d/source" ] || { echo "missing dub package $d (run dub build in mobile/ once)" >&2; exit 1; }
    P2P_INCLUDES="$P2P_INCLUDES -I$DUBP/$d/source"
    P2P_SOURCES="$P2P_SOURCES $(find "$DUBP/$d/source" -name '*.d')"
done
ABI_DIR=arm64

link() {
    # -shared: Qt for Android loads lib<app>_<abi>.so and calls its exported main().
    # -relocation-model=pic: everything in a .so must be PIC (the binding archive was built so too).
    # qrc.d is compiled in (not only imported) or the link wants "ModuleInfo for qrc".
    cd "$HERE"
    ldc2 -conf="$LDC_CONF" -mtriple=aarch64-linux-android -shared -relocation-model=pic -O \
        -d-version=PhotoWagonMobile \
        -of="$OUT/lib${APP}_${ABI}.so" \
        source/photowagon/mobile/main.d source/photowagon/mobile/plog.d source/photowagon/mobile/tcpbridge.d \
        source/photowagon/mobile/p2pbridge.d \
        source/photowagon/mobile/localbridge.d source/photowagon/mobile/phoneindex.d \
        ../source/photowagon/ui/backend.d ../source/photowagon/ui/transport.d ../source/photowagon/ui/bridge.d \
        ../source/photowagon/core/ipc/link.d ../source/photowagon/core/p2p/identity.d \
        $P2P_SOURCES -d-version=LibP2P_Lite $P2P_INCLUDES \
        ../source/photowagon/core/indexer/scan.d ../source/photowagon/core/library/calendar.d \
        ../source/photowagon/core/metadata/exifparse.d ../source/photowagon/core/pairingcode.d \
        "$DSIDE/runtime/qrc/qrc.d" \
        -Isource -I../source -I"$GEN" -I"$DSIDE/runtime/qrc" -J=../qml \
        -L--gc-sections -L--as-needed \
        -L--start-group -L="$BUILD/libbinding_ldc2.a" -L="$BUILD/libshims.a" -L--end-group \
        -L="$HERE/toolchain/android-libs/$ABI_DIR/libsodium.a" \
        -L-L"$QT_ANDROID/lib" \
        -L-lQt6Quick_${ABI} -L-lQt6QmlModels_${ABI} -L-lQt6Qml_${ABI} -L-lQt6Network_${ABI} \
        -L-lQt6Gui_${ABI} -L-lQt6Core_${ABI} \
        -L-lc++_shared -L-llog -L-landroid
    "$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-nm" -D "$OUT/lib${APP}_${ABI}.so" | grep -q ' T main$'
    echo "-> $OUT/lib${APP}_${ABI}.so"
}

settings() {
    # Modelled on a qt-cmake generated deployment file; absolute paths are required.
    cat > "$OUT/android-deployment-settings.json" <<EOF
{
   "description": "androiddeployqt settings for Photo Wagon mobile (generated by build-android.sh)",
   "qt": { "$ABI": "$QT_ANDROID" },
   "qtDataDirectory": { "$ABI": "." },
   "qtLibExecsDirectory": { "$ABI": "libexec" },
   "qtLibsDirectory": { "$ABI": "lib" },
   "qtPluginsDirectory": { "$ABI": "plugins" },
   "qtQmlDirectory": { "$ABI": "qml" },
   "sdk": "$ANDROID_SDK_ROOT",
   "sdkBuildToolsRevision": "36.0.0",
   "ndk": "$NDK",
   "toolchain-prefix": "llvm",
   "tool-prefix": "llvm",
   "useLLVM": true,
   "toolchain-version": "clang",
   "ndk-host": "linux-x86_64",
   "abi": "$ABI",
   "architectures": { "$ABI": "aarch64-linux-android" },
   "android-legacy-packaging": true,
   "android-package-source-directory": "$HERE/android",
   "android-package-name": "$PKG_NAME",
   "android-app-name": "Photo Wagon",
   "android-version-name": "0.4.0",
   "android-version-code": "4",
   "permissions": [ { "name": "android.permission.INTERNET" } ],
   "application-binary": "$APP",
   "qml-root-path": [ "$HERE/../qml" ],
   "qml-importscanner-binary": "$QT_HOST/libexec/qmlimportscanner",
   "qml-dom-binary": "$QT_HOST/bin/qmldom",
   "rcc-binary": "$QT_HOST/libexec/rcc",
   "extraPrefixDirs": [ "$QT_ANDROID" ],
   "extraLibraryDirs": [ ],
   "zstdCompression": false,
   "generate-java-qtquickview-contents": false,
   "stdcpp-path": "$NDK/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/"
}
EOF
}

package() {
    settings
    mkdir -p "$OUT/pkg/libs/$ABI"
    cp "$OUT/lib${APP}_${ABI}.so" "$OUT/pkg/libs/$ABI/"
    # android-36: the androidx.core the Qt template pulls in requires compileSdk >= 36.
    "$QT_HOST/bin/androiddeployqt" --input "$OUT/android-deployment-settings.json" \
        --output "$OUT/pkg" --android-platform android-36 --gradle
    cp "$OUT/pkg/build/outputs/apk/debug/pkg-debug.apk" "$OUT/photo-wagon-mobile-debug.apk"
    echo "-> $OUT/photo-wagon-mobile-debug.apk"
}

run() {
    adb install -r "$OUT/photo-wagon-mobile-debug.apk"
    adb logcat -c
    adb shell am start -n "$PKG_NAME/.MainActivity"
    sleep 8
    adb exec-out screencap -p > "$OUT/phone.png"
    echo "-> $OUT/phone.png"
    adb logcat -d | grep -E 'bridge:|qml rootObjects|D qml|AndroidRuntime|FATAL|photowagon' | tail -20
}

case "${1:-all}" in
    link) link ;;
    package) package ;;
    run) run ;;
    all) link; package; run ;;
    *) echo "usage: $0 [link|package|run|all]" >&2; exit 2 ;;
esac
