#!/usr/bin/env python3
"""Capture the real Android APK in an existing headless Waydroid session."""

import argparse
import base64
import json
import os
from pathlib import Path
import shutil
import struct
import subprocess
import tempfile
import time

from demo_ipc import DemoCore

ROOT = Path(__file__).resolve().parent.parent
PACKAGE = "org.photowagon.mobile"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--serial", required=True, help="Explicit Waydroid ADB address")
    parser.add_argument("--work", required=True, type=Path, help="Library prepared by tools/demo.py")
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--apk", type=Path, help="Install this debug x86_64 APK first")
    args = parser.parse_args()
    work, output = args.work.resolve(), args.output.resolve()
    if not (work / "demo.json").is_file():
        parser.error("--work must be an existing generated demo library")
    output.mkdir(parents=True, exist_ok=True)

    def adb(*command, binary=False):
        return subprocess.check_output(["adb", "-s", args.serial, *map(str, command)],
                                       text=not binary, timeout=90)

    model = adb("shell", "getprop", "ro.product.model").strip()
    if "waydroid" not in model.lower():
        parser.error(f"Refusing to change a non-Waydroid device: {model}")
    if args.apk:
        print(adb("install", "-r", args.apk.resolve()), flush=True)
    for permission in ("READ_MEDIA_IMAGES", "READ_MEDIA_VIDEO", "POST_NOTIFICATIONS"):
        adb("shell", "pm", "grant", PACKAGE, "android.permission." + permission)

    # Keep other camera-roll fixtures intact. Original generated bytes also match
    # the hashes imported by the core, unlike desktop copies after XMP writeback.
    entries = json.loads((ROOT / "docs/demo-photos/library.json").read_text())
    with tempfile.TemporaryDirectory(prefix="pw-android-photos-") as staging:
        folder = Path(staging) / "PhotoWagonDemoAI"
        for entry in entries:
            target = folder / entry["date"] / entry["file"]
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(ROOT / "docs/demo-photos" / entry["file"], target)
        print(adb("push", folder, "/sdcard/Pictures/"), flush=True)

    old_size = adb("shell", "wm", "size")
    old_density = adb("shell", "wm", "density")

    def restore(setting, previous):
        override = [line.split(":", 1)[1].strip() for line in previous.splitlines()
                    if line.startswith("Override")]
        adb("shell", "wm", setting, override[0] if override else "reset")

    def tap(x, y):
        adb("shell", "input", "tap", x, y)
        time.sleep(1)

    def capture(name):
        data = adb("exec-out", "screencap", "-p", binary=True)
        if data[:8] != b"\x89PNG\r\n\x1a\n" or struct.unpack(">II", data[16:24]) != (1080, 2400):
            raise RuntimeError("Expected a full 1080x2400 Android screenshot")
        (output / name).write_bytes(data)
        print(f"Captured {output / name}", flush=True)

    env = dict(os.environ, XDG_CONFIG_HOME=str(work / "config"),
               XDG_DATA_HOME=str(work / "data"), XDG_CACHE_HOME=str(work / "cache"))
    command = [str(ROOT / "photo-wagon"), "--data", str(work / "library"),
               "--runtime", str(work / "runtime"), "--models", str(work / "models"),
               "--no-p2p", "--jobs", "2"]
    reverse_port = None
    try:
        adb("shell", "wm", "size", "1080x2400")
        adb("shell", "wm", "density", "420")
        adb("shell", "am", "force-stop", PACKAGE)
        with DemoCore(command, work, env) as core:
            reverse_port = adb("reverse", "tcp:0", f"tcp:{core.port}").strip()
            variables = ("PW_PHONE_ROOTS=/sdcard/Pictures/PhotoWagonDemoAI "
                         f"PW_ENDPOINT=127.0.0.1:{reverse_port} QT_FORCE_STDERR_LOGGING=1")
            adb("shell", "am", "start", "-n", PACKAGE + "/.MainActivity", "--es",
                "extraenvvars", base64.b64encode(variables.encode()).decode())
            print("Waiting for Android indexing and the on-device face pass…", flush=True)
            time.sleep(35)
            pid = adb("shell", "pidof", PACKAGE).strip()
            if not pid:
                raise RuntimeError("The Android app exited")
            capture("mobile.png")
            tap(540, 2170)  # Search: named people and their real portraits.
            capture("android-people.png")
            tap(180, 2170)
            tap(180, 500)   # First photo: Alice, Nina and Leo at the picnic.
            time.sleep(2)
            capture("android-viewer.png")
            logs = adb("logcat", "-d", "--pid=" + pid)
            (work / "android-demo.log").write_text(logs)
            if "crash: signal" in logs or "FATAL EXCEPTION" in logs:
                raise RuntimeError(f"Android crashed; see {work / 'android-demo.log'}")
            print("Android captures complete; app remained alive during navigation.", flush=True)
    finally:
        adb("shell", "am", "force-stop", PACKAGE)
        if reverse_port:
            adb("reverse", "--remove", "tcp:" + reverse_port)
        restore("size", old_size)
        restore("density", old_density)


if __name__ == "__main__":
    main()
